services:
  # Celery worker
  celery-worker:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - ${SECRETS_DIR}:/secrets:ro

    command: celery -A api worker --concurrency=4 -E

  # Celery beat scheduler
  celery-beat:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    command: celery -A api beat 