# Generated by Django 5.2.1 on 2025-05-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_text', models.TextField()),
                ('source_url', models.URLField(unique=True)),
                ('date_published', models.DateTimeField()),
                ('pib_hq', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.audiencetype')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('ministry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil')], max_length=10)),
                ('text_type', models.CharField(choices=[('original', 'Original'), ('simplified', 'Simplified'), ('oversimplified', 'Over Simplified'), ('summary', 'Summary'), ('keypoints', 'Key Points')], max_length=50)),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('press_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.pressrelease')),
            ],
            options={
                'unique_together': {('press_release', 'language', 'text_type')},
            },
        ),
    ]
