# Generated by Django 5.2.1 on 2025-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_translatedtext_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressrelease',
            name='category',
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='category',
            field=models.ManyToManyField(to='core.category'),
        ),
    ]
