# Generated by Django 5.2.1 on 2025-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pressrelease_category_pressrelease_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressrelease',
            name='audience_type',
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='audience_type',
            field=models.ManyToManyField(to='core.audiencetype'),
        ),
    ]
