# Generated by Django 5.2.1 on 2025-05-25 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pressrelease_audience_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedtext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatedtext',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
