# Generated by Django 5.2.1 on 2025-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_translatedtext_created_at_translatedtext_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedtext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('or', 'Odia'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('pa', 'Punjabi'), ('te', 'Telugu')], max_length=10),
        ),
    ]
