# Generated by Django 5.2.1 on 2025-05-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_translatedtext_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='date_published',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='translatedtext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('or', 'Odia'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('pa', 'Punjabi'), ('te', 'Telugu')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='translatedtext',
            name='text_type',
            field=models.CharField(choices=[('original', 'Original'), ('simplified', 'Simplified'), ('oversimplified', 'Over Simplified'), ('summary', 'Summary'), ('keypoints', 'Key Points')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='pressrelease',
            index=models.Index(fields=['-date_published'], name='core_pressr_date_pu_780e77_idx'),
        ),
        migrations.AddIndex(
            model_name='pressrelease',
            index=models.Index(fields=['date_published', 'title', 'ministry_id'], name='press_release_common_idx'),
        ),
        migrations.AddIndex(
            model_name='pressrelease',
            index=models.Index(condition=models.Q(('date_published__gte', '2024-01-01')), fields=['date_published'], name='recent_press_releases_idx'),
        ),
        migrations.AddIndex(
            model_name='translatedtext',
            index=models.Index(fields=['press_release', 'language', 'text_type'], name='core_transl_press_r_e3dcc6_idx'),
        ),
    ]
