# Generated by Django 5.2.1 on 2025-05-28 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pressrelease_date_published_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pressrelease',
            name='recent_press_releases_idx',
        ),
        migrations.AddIndex(
            model_name='pressrelease',
            index=models.Index(condition=models.Q(('date_published__gte', datetime.datetime(2023, 12, 31, 18, 30, tzinfo=datetime.timezone.utc))), fields=['date_published'], name='recent_press_releases_idx'),
        ),
    ]
