# Generated by Django 5.2.1 on 2025-05-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pressrelease_recent_press_releases_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
